runtime: nodejs10
beta_settings:
  cloud_sql_instances: ybk-site:us-east1:database
env_variables:
  SQL_USER: root
  SQL_PASSWORD: olsmas10612
  SQL_DATABASE: database
  INSTANCE_CONNECTION_NAME: ybk-site:us-east1:database
handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
